### ISSUE TITLE
Maximum response length

### ISSUE THREAD

**Issue by Quidos** [blha303/srcomapi#18]
Hi! 
I'm kind of new to REST APIs but I noticed that sometimes not all data is returned in one http request, because max value is set to 20. So there are problems if for example a category has over 20 levels.
An easy fix is to set a max parameter above 20 like this:
https://www.speedrun.com/api/v1/categories/7dg5vw72/records?max=100

**Comment by cmnemoi** [comment]
It's a little more complicated than that, as the maximum results allowed by SRC is 200. 
If your request has more than 200 results you have to send other ones through offsets until you get them all : https://github.com/speedruncomorg/api/blob/master/version1/pagination.md

I sent a PR if @blha303 wants to fix that

**Comment by alyssadev** [comment]
I've got a new github account (this one), haven't looked at my old projects for a while, I'll review the PR now
