### ISSUE TITLE
Get WR records

### ISSUE THREAD

**Issue by Jsevillamol** [blha303/srcomapi#20]
Hi! Thank you so much for writing this tool, I've found it very helpful.

I wanted to ask if there is a direct way of getting the data for WR progressions, as in the gamestat page of each game ([example](https://www.speedrun.com/sms/gamestats)).

Concretely, I would like to end up with a list of dictionary entries, where each dictionary is of the form 

```
{
'game' : 'Super Mario Sunshine', 
'category' : 'any%', 
'time' : <primary_t>,
'date'; <date>,
'runner' : '<player.id(s)>',
}
```

I tried downloading all runs with the intention of filtering them myself later to only include world record improvements, as this:

```
import srcomapi, srcomapi.datatypes as dt

api = srcomapi.SpeedrunCom(); api.debug = 1
search_results = api.search(srcomapi.datatypes.Game, {"name": "super mario sunshine"})
game = search_results[0]
category = game.categories[0]
leaderboard = dt.Leaderboard(api, data=api.get(f"leaderboards/{game.id}/category/{category.id}?embed=variables"))

data = []
for run in leaderboard.runs:
  run = run['run']
  row = {'date' : run.date,
         'time' : run.times['primary_t'],
         'runner' : ", ".join([player.name for player in run.players])}
  data.append(row)
```

But this method is very slow.

**Comment by alyssadev** [comment]
You're right that iterating over runs is crazy slow, but there doesn't seem to be a decent API way of getting that data. https://github.com/speedruncomorg/api/issues/123

One (kinda gross) option would be, download the source for the webpage at `f"https://www.speedrun.com/{game.abbreviation}/gamestats"`, filter out the line with `var runs =`, and load that array as json.

**Comment by alyssadev** [comment]
That being said, getting runs doesn't *have* to be slow, right now Leaderboard.runs is requesting info for every run, that could be averted by reimplementing .runs to use the data from the variables embed maybe

**Comment by Jsevillamol** [comment]
Retrieving the runs directly from the stats page is a cool idea!

One thing I am struggling to solve is how to decode the times and dates (which are in an eccentric format)
Can I somehow use the API to get information about particular runs given the link to the run?

Eg how could I download the information associated to run `https://www.speedrun.com/sms/run/20422` using the API?

**Comment by alyssadev** [comment]
I'm not sure how `20422` translates to any data in the api, but getting the headers from requesting `https://www.speedrun.com/sms/run/20422` shows `location: /sms/run/dy45xqdm`, that ID could then be parsed out and used in `run = dt.Run(api, api.get(f"runs/{id}"))`.

I'll be the first to admit that 1. there should be an API way to translate from that numeric ID (which I haven't seen before tbh; all IDs on speedrun.com are meant to be the eight character alphanumeric type) and 2. just in general, fetching a specific record (in the database sense) by ID is clunky with the current implementation. I wrote this library so many years ago and there's many things I'd do differently if I wrote it today.

**Comment by alyssadev** [comment]
Additionally, the x and y values in the graph data are time and seconds, i.e x = int(datetime.strptime(run.date, "%Y-%m-%d").timestamp()), y = run.times["primary_t"]

**Comment by exodustx0** [comment]
> One (kinda gross) option would be, download the source for the webpage at `f"https://www.speedrun.com/{game.abbreviation}/gamestats"`, filter out the line with `var runs =`, and load that array as json.

I'd like to point out, for the sake of questionable robustness, that if you *do* decide to go that route, you should use `f"{game.weblink}/gamestats"` instead of `f"https://www.speedrun.com/{game.abbreviation}/gamestats"` as the [`Game`](https://github.com/speedruncomorg/api/blob/master/version1/games.md) structure documentation notes.

**Comment by Jsevillamol** [comment]
For the sake of future people, here is a Python script that downloads the data for the 100 most popular videogames, for categories where there has been at least 10 improvements to the world record. And here is a [snapshot of the script's output from 27/07/2021](https://drive.google.com/file/d/1P77mj6ajBDLtnicLDiqUSBBmVljEamaG/view?usp=sharing).

```
import urllib.request
import re
import ast
import pandas as pd
from bs4 import BeautifulSoup
from tqdm.notebook import tqdm

N_GAMES = 100
# Get most popular speedrunning games
most_popular_games = []
for step in range(0, N_GAMES, 50):
  ajax_request = f'https://www.speedrun.com/ajax_games.php?unofficial=off&orderby=mostruns&start={step}'
  response = urllib.request.urlopen(ajax_request)
  soup = BeautifulSoup(response, 'html.parser')
  most_popular_games += [link.get('href') for link in soup.find_all('a') if link.get('href') is not None]

# Iterate over all WR progression of more popular games and store new world record run information
data = []
for game_id in tqdm(most_popular_games):

  # Retrive name of game
  game_url = f"https://www.speedrun.com/{game_id}"
  response = urllib.request.urlopen(game_url)
  soup = BeautifulSoup(response, 'html.parser')
  game_title = re.match(r'(.*) - speedrun.com', soup.title.string).group(1)

  print(f"Downloading data for {game_title}", end="")

  # Retrive stats page of game
  game_stats_url = f"https://www.speedrun.com/{game_id}/gamestats"
  response = urllib.request.urlopen(game_stats_url)
  page_source = response.read().decode('utf-8')

  # Extract data about WR progression
  m = re.search(r'var runs = (.*);', page_source).group(1)
  m = m.replace("true", "True")
  m = m.replace("false", "False")
  d = ast.literal_eval(m)
  
  if type(d) is dict:
    full_game_data = d['0'] # The '0' key is the full game data
                            # The rest are individual levels  
  else: # Only the full game data is available    
    full_game_data = d[0]

  for category in full_game_data:
    category_label = category['label']
    #print(f"Downloading data for {game_title} - {category_label}")
    for run in category['data']:
      run_link = run['link']
      run_url = 'https://www.speedrun.com' + run_link.replace('\\', '')
      time = run['y']
      date = run['x'] # gmtime(run['x'])
      runners = ', '.join(run['players'])

      # Add entry to dataset
      entry = {
          "game" : game_title,
          "category" : category_label,
          "time (seconds)" : time,
          "date (unix)" : date,
          "runner" : runners,
          "url" : run_url,
      }
      data.append(entry)
  print("\r", end="")
  print("                                                             ", end="")

df = pd.DataFrame(data)

# Recode columns
df['date'] = pd.to_datetime(df['date (unix)'],unit='s')

# Select runs from categories where the record has been improved at least 10 times
group_mask = df.groupby(['game', 'category']).size()>=10
mask = df.apply(lambda row : group_mask[row['game'], row['category']], axis=1)
df = df[mask]

# Print dataset information
n_games = len(df.groupby('game'))
n_categories = len(df.groupby(['game', 'category']))
n_runs = len(df)
print(f"There are {n_games} games, {n_categories} categories and {n_runs} runs")

# Save to CSV
df.to_csv('WR_improvements.csv')
```
