### ISSUE TITLE
Proposal: Add search methods for games and users

### ISSUE THREAD

**Issue by lepelog** [blha303/srcomapi#6]
Currently there is only a way to get all games or a specific game by its id or abbreviation, but games should be searchable by name and a lot of other parameters listed in the Speedrun.com API-documentation. Same with users.

**Comment by blha303** [comment]
There's already a method in srcomapi.SpeedrunCom that lets you search for games, `api.get_games(params={"name": "super mario sunshine"})` returns all matches for that game in a generator that can be iterated over. An additional convenience function can be created for Users, or a generic function that can take a Datatype class and use the endpoint and given parameters to return a list of models.

**Comment by blha303** [comment]
https://github.com/blha303/srcomapi/commit/87ff8a69a96fb1818310f3d358fd5b8d8f71de92

```
>>> import srcomapi
>>> api = srcomapi.SpeedrunCom()
>>> next(api.search(srcomapi.datatypes.Game, {"name": "super mario sunshine"}))
<Game "Super Mario Sunshine">
>>> list(api.search(srcomapi.datatypes.Game, {"name": "super mario sunshine"}))
[<Game "Super Mario Sunshine">]
>>> list(api.search(srcomapi.datatypes.User, {"name": "fearfulferret"}))
[<User "0jm69e81">]
```
