### ISSUE TITLE
Bug with get_game

### ISSUE THREAD

**Issue by lepelog** [blha303/srcomapi#9]
```python
>>> import srcomapi
>>> api=srcomapi.SpeedrunCom()
>>> api.get_games()
```
results in an error, same with `api.get_game`

**Comment by blha303** [comment]
Those are legacy functions, as indicated in the docstring for each:

    >>> help(api.get_game)
    Help on method get_game in module srcomapi.srcomapi:
    get_game(id, **kwargs) method of srcomapi.srcomapi.SpeedrunCom instance
        Legacy function, will be removed in next major version

I'll push a fix, but the recommended method now is to use

    import srcomapi
    import srcomapi.datatypes as dt
    api = srcomapi.SpeedrunCom()
    game = api.search(dt.Game, {"name": "Super Mario Sunshine"})

Currently this does not support using IDs directly, I need to fix that. The [tests file](https://github.com/blha303/srcomapi/blob/master/test_srcomapi.py) is a good indication of the desired usage of the library.
